// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type File struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type Folder struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Files []*File `json:"files"`
}

type Query struct {
}

type Root struct {
	Folders []*Folder `json:"folders"`
	Files   []*File   `json:"files"`
}

type Subscription struct {
}
